config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root "flights#index"
  resources :flights, only: [:index]

  resources :bookings, only: [:new, :create, :show]
end

app/models/airpot.rb
class Airport < ApplicationRecord
    has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id', dependent: :destroy
    has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id', dependent: :destroy
  
    validates :code, presence: true, uniqueness: true
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight
    has_many :passengers, dependent: :destroy
  
    accepts_nested_attributes_for :passengers
  
    validates :flight, :passengers, presence: true
    # validates :passengers, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 4}
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'
    belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
    has_many :bookings, dependent: :destroy
  
    validates :departure_airport, :arrival_airport, :start_datetime, presence: true
    validates :passengers, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 4}
    validate :start_datetime_in_range
  
    private
  
    def start_datetime_in_range
        if start_datetime < Date.today || start_datetime > Date.today + 23.days
           errors.add(:start_datetime, "must be within 23 days from today")
        end
    end
end
  

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
  
    validates :name, :email, presence: true
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
      @flight = Flight.find(params[:flight_id])
      @booking = @flight.bookings.build
      passengers = params[:passengers].to_i
      passengers.times { @booking.passengers.build }
    end
  
    def create
      @flight = Flight.find(params[:booking][:flight_id])
      @booking = @flight.bookings.build(booking_params)
      if @booking.save
        @booking.passengers.each do |passenger|
          PassengerMailer.with(passenger: passenger, booking: @booking).ticket_email.deliver_now
        end
        redirect_to @booking
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def show
      @booking = Booking.find(params[:id])
    end
  
    private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
    end
end
  

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

  def index
    if params[:flight]
          @flights = Flight.where(departure_airport_id: params[:flight][:departure_airport_id],
                              arrival_airport_id: params[:flight][:arrival_airport_id],)
                              .where("DATE(start_datetime) = ?", params[:start_datetime])
    else
         @flights = Flight.all
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_passenger_fields.html.erb
<div class="passenger-field" data-controller="passenger" > 
    <h4>Passenger Information</h4>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <button data-action="click->passenger#removePassenger">Remove Passenger</button>
</div>

app/views/bookings/new.html.erb
<%= form_with(model: @booking, url: bookings_path, local: true, data: {controller: "passenger"} )do |f| %>
    <%# errors%>
    <% if @booking.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

            <ul>
                <% @booking.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <h2>Book Flight</h2>

    <p>
        Flight ID: <%= @flight.id %><br>
        Departure Airport: <%= @flight.departure_airport.code %><br>
        Arrival Airport: <%= @flight.arrival_airport.code %><br>
        Start Date: <%= @flight.start_datetime %>
    </p>

    <%= f.hidden_field :flight_id, value: @flight.id %>

    <div data-passenger-target="container" >
        <%= f.fields_for :passengers do |passenger_form| %>
            <%= render 'passenger_fields', f: passenger_form %>
        <% end %>
    </div>

    <template data-passenger-target="template" >
        <%= f.fields_for :passengers, Passenger.new, child_index: 'NEW_RECORD' do |passenger_form| %>
            <%= render 'passenger_fields', f: passenger_form %>
        <% end %>
    </template>

    <button data-action="click->passenger#addPassenger">Add Passenger</button>

    <br><br>
    <%= f.submit "Create Booking" %>
<% end %>

app/views/bookings/show.html.erb
<h2>Booking Information</h2>

<p>
    Flight ID: <%= @booking.flight_id %><br>
    Departure Airport: <%= @booking.flight.departure_airport.code %><br>
    Arrival Airport: <%= @booking.flight.arrival_airport.code %><br>
    Start Date: <%= l(@booking.flight.start_datetime, format: :long) %><br>
</p>

<h2>Passenger Information</h2>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <% @booking.passengers.each do |passenger| %>
            <tr>
                <td><%= passenger.name %></td>
                <td><%= passenger.email %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<p>
    <%= link_to 'Back to Flights', flights_path %>
</p>

<style>
    body {
        font-family: Arial, sans-serif;
    }

    h2 {
        color: #333;
        margin-bottom: 20px;
    }

    p {
        color: #666;
        line-height: 1.6;
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 20px;
    }

    table th, table td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    table th {
        background-color: #f2f2f2;
        color: #333;
    }

    table tr:nth-child(even) {
        background-color: #f2f2f2;
    }
</style>

app/views/flights/index.html.erb
<h1>Flight Booker</h1>

<%= form_with url: flights_path, method: :get do %>
    <h2>Flight Details</h2>
    <%= label_tag :departure_airport %>
    <%= collection_select :flight, :departure_airport_id, Airport.all, :id, :code, prompt: true %>

    <%= label_tag :arrival_airport %>
    <%= collection_select :flight, :arrival_airport_id, Airport.all, :id, :code, prompt: true %>

    <%= label_tag :passengers, 'Tickets'%>
    <%= select_tag :passengers, options_for_select([1, 2, 3, 4]) %>

    <%= label_tag :start_datetime, 'Start Date' %>
    <%# collection_select :flight, :start_datetime, Flight.all, :start_datetime, :start_datetime, prompt: true, selected: params[:flight]&.[](:start_datetime) %>
    <%= select_tag :start_datetime, options_for_select(Flight.pluck(:start_datetime).map { |datetime| datetime.to_date }.uniq.sort), prompt: 'Select date' %>
    <%# date_field_tag :start_datetime, params[:start_datetime] %>

    <%= submit_tag "Search" %>
<% end %>

<% if @flights.any? %>
    <h2>Available Flights</h2>
    <%= form_with url: new_booking_path, method: :get do %>
        <%= hidden_field_tag :passengers, params[:passengers] %>
        <% @flights.each do |flight| %>
            <%= radio_button_tag :flight_id, flight.id %>
            <%= label_tag "flight_#{flight.id}", "#{flight.departure_airport.code} to #{flight.arrival_airport.code} on #{flight.start_datetime.strftime("%B %d, %Y at %I:%M %p")} Duration: #{flight.flight_duration}hrs" %>
            <br>
        <% end %>
        <%= submit_tag "Book Flight" %>
    <% end %>
<% else %>
    <h3>No flights available</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
       <title>FlightBookerOdin</title>
       <meta name="viewport" content="width=device-width,initial-scale=1">
       <%= csrf_meta_tags %>
       <%= csp_meta_tag %>

       <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
       <%= javascript_importmap_tags %>
    </head>

    <body>
       <%= link_to "Home", root_path %>
       <%= yield %>
    </body>
</html>